# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hugo/Desktop/project 3278/Login_History.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginHistory(object):
    def setupUi(self, LoginHistory):
        LoginHistory.setObjectName("LoginHistory")
        LoginHistory.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(LoginHistory)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textBrowser_loginhistory = QtWidgets.QTextBrowser(LoginHistory)
        self.textBrowser_loginhistory.setGeometry(QtCore.QRect(30, 20, 341, 211))
        self.textBrowser_loginhistory.setObjectName("textBrowser_loginhistory")

        self.retranslateUi(LoginHistory)
        self.buttonBox.accepted.connect(LoginHistory.accept)
        self.buttonBox.rejected.connect(LoginHistory.reject)
        QtCore.QMetaObject.connectSlotsByName(LoginHistory)

    def retranslateUi(self, LoginHistory):
        _translate = QtCore.QCoreApplication.translate
        LoginHistory.setWindowTitle(_translate("LoginHistory", "Login History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginHistory = QtWidgets.QDialog()
    ui = Ui_LoginHistory()
    ui.setupUi(LoginHistory)
    LoginHistory.shoo()
    sys.exit(app.exec_())
