# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hugo/Desktop/project 3278/Main window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from customer.pyfile_copy.transfer import Ui_Transfer
from customer.pyfile_copy.show import Ui_Yourac
from customer.pyfile_copy.profile import Ui_Profile
from customer.pyfile_copy.login import Ui_LoginHistory
from customer.pyfile_copy.searching import Ui_Searching

import sys
from PyQt5.QtWidgets import (QApplication, QWidget, QMessageBox)

class Customer_Main(object):

    def __init__(self, username):
        super().__init__()
        self.username = username

    def transfer(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Transfer()
        self.ui.setupUi(self.window)
        self.window.show()

    def showAccount(self):
       self.window = QtWidgets.QDialog()
       self.ui = Ui_Yourac()
       self.ui.setupUi(self.window)
       self.window.show()

    def profile(self):
       self.window = QtWidgets.QDialog()
       self.ui = Ui_Profile()
       self.ui.setupUi(self.window)
       self.window.show()

    def loginhistory(self):
       self.window = QtWidgets.QDialog()
       self.ui = Ui_LoginHistory()
       self.ui.setupUi(self.window)
       self.window.show()

    def searching(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Searching()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 505)
        MainWindow.setMaximumSize(QtCore.QSize(561, 505))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(5000, 5000))
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Logout.setGeometry(QtCore.QRect(360, 320, 171, 32))
        self.pushButton_Logout.setMaximumSize(QtCore.QSize(171, 16777215))
        self.pushButton_Logout.setObjectName("pushButton_Logout")


        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 90, 491, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_CheckAllAccount = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_CheckAllAccount.setMaximumSize(QtCore.QSize(481, 16777215))
        self.pushButton_CheckAllAccount.setObjectName("pushButton_CheckAllAccount")
        self.verticalLayout.addWidget(self.pushButton_CheckAllAccount)

        self.pushButton_CheckAllAccount.clicked.connect(self.showAccount)

        self.pushButton_Balance = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Balance.setMaximumSize(QtCore.QSize(481, 16777215))
        self.pushButton_Balance.setObjectName("pushButton_Balance")
        self.verticalLayout.addWidget(self.pushButton_Balance)

        self.pushButton_Balance.clicked.connect(self.searching)

        self.pushButton_Transfer = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Transfer.setMaximumSize(QtCore.QSize(481, 16777215))
        self.pushButton_Transfer.setObjectName("pushButton_Transfer")
        self.verticalLayout.addWidget(self.pushButton_Transfer)

        self.pushButton_Transfer.clicked.connect(self.transfer)

        self.pushButton_Profile = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Profile.setMaximumSize(QtCore.QSize(481, 16777215))
        self.pushButton_Profile.setObjectName("pushButton_Profile")
        self.verticalLayout.addWidget(self.pushButton_Profile)

        self.pushButton_Profile.clicked.connect(self.profile)

        self.pushButton_LoginHistory = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_LoginHistory.setMaximumSize(QtCore.QSize(481, 16777215))
        self.pushButton_LoginHistory.setObjectName("pushButton_LoginHistory")
        self.verticalLayout.addWidget(self.pushButton_LoginHistory)

        self.pushButton_LoginHistory.clicked.connect(self.loginhistory)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 50, 271, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.pushButton_Logout.clicked.connect(self.closeEvent)

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Logout.setText(_translate("MainWindow", "Logout"))
        self.pushButton_CheckAllAccount.setText(_translate("MainWindow", "Check All Account"))
        self.pushButton_Balance.setText(_translate("MainWindow", "Balance"))
        self.pushButton_Transfer.setText(_translate("MainWindow", "Transfer"))
        self.pushButton_Profile.setText(_translate("MainWindow", "Profile"))
        self.pushButton_LoginHistory.setText(_translate("MainWindow", "Login History"))
        self.label.setText(_translate("MainWindow", "WELCOME TO YOUR BANK ACCOUNT!"))

    def askWindow(self, text, quesetion):
        msg = QMessageBox()
        msg.setText(quesetion)
        msg.setStandardButtons(QMessageBox.Yes|QMessageBox.No)
        msg.setDefaultButton(QMessageBox.No)
        return msg.exec()

    def closeEvent(self):
        if (self.askWindow("Window Close",
                           "Are you sure you want to close the window?") == QMessageBox.Yes):
            # DO Sth
            pass
        # reply = QMessageBox.question(self,
        #                              'Window Close',
        #                              'Are you sure you want to close the window?',
        #                              QMessageBox.Yes | QMessageBox.No,
        #                              QMessageBox.No)

        # if reply == QMessageBox.Yes:
        #     event.accept()
        #     print('Window closed')
        # else:
        #     event.ignore()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Customer_Main()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
