# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hugo/Desktop/project 3278/Profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Profile(object):
    def setupUi(self, Profile):
        Profile.setObjectName("Profile")
        Profile.resize(500, 392)
        self.buttonBox = QtWidgets.QDialogButtonBox(Profile)
        self.buttonBox.setGeometry(QtCore.QRect(390, 30, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textBrowser = QtWidgets.QTextBrowser(Profile)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 361, 341))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Profile)
        self.buttonBox.accepted.connect(Profile.accept)
        self.buttonBox.rejected.connect(Profile.reject)
        QtCore.QMetaObject.connectSlotsByName(Profile)

    def retranslateUi(self, Profile):
        _translate = QtCore.QCoreApplication.translate
        Profile.setWindowTitle(_translate("Profile", "Profile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Profile = QtWidgets.QDialog()
    ui = Ui_Profile()
    ui.setupUi(Profile)
    Profile.shoo()
    sys.exit(app.exec_())
