# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hugo/Desktop/project 3278/Searching.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Searching(object):
    def setupUi(self, Searching):
        Searching.setObjectName("Searching")
        Searching.resize(518, 712)
        self.gridLayoutWidget = QtWidgets.QWidget(Searching)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 150, 121, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_Daychoosing = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_Daychoosing.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Daychoosing.setObjectName("gridLayout_Daychoosing")
        self.label_Search_To = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Search_To.setObjectName("label_Search_To")
        self.gridLayout_Daychoosing.addWidget(self.label_Search_To, 2, 0, 1, 1)
        self.label_Search_From = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Search_From.setObjectName("label_Search_From")
        self.gridLayout_Daychoosing.addWidget(self.label_Search_From, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Searching)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(80, 80, 121, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_Acchoosing = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_Acchoosing.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Acchoosing.setObjectName("gridLayout_Acchoosing")
        self.label_Account = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_Account.setObjectName("label_Account")
        self.gridLayout_Acchoosing.addWidget(self.label_Account, 0, 0, 1, 1)
        self.label_Currency = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_Currency.setObjectName("label_Currency")
        self.gridLayout_Acchoosing.addWidget(self.label_Currency, 1, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Searching)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(200, 80, 241, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_AC = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_AC.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_AC.setObjectName("gridLayout_AC")
        self.comboBox_Account = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBox_Account.setObjectName("comboBox_Account")
        self.comboBox_Account.addItem("")
        self.comboBox_Account.addItem("")
        self.gridLayout_AC.addWidget(self.comboBox_Account, 1, 0, 1, 1)
        self.comboBox_Currency = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBox_Currency.setObjectName("comboBox_Currency")
        self.comboBox_Currency.addItem("")
        self.comboBox_Currency.addItem("")
        self.comboBox_Currency.addItem("")
        self.gridLayout_AC.addWidget(self.comboBox_Currency, 2, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Searching)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(200, 150, 241, 81))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_DAY = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_DAY.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_DAY.setObjectName("gridLayout_DAY")
        self.dateEdit_Search_From = QtWidgets.QDateEdit(self.gridLayoutWidget_4)
        self.dateEdit_Search_From.setObjectName("dateEdit_Search_From")
        self.gridLayout_DAY.addWidget(self.dateEdit_Search_From, 0, 0, 1, 1)
        self.dateEdit_Search_To = QtWidgets.QDateEdit(self.gridLayoutWidget_4)
        self.dateEdit_Search_To.setObjectName("dateEdit_Search_To")
        self.gridLayout_DAY.addWidget(self.dateEdit_Search_To, 1, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(Searching)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 20, 171, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_SYT = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_SYT.setObjectName("label_SYT")
        self.verticalLayout.addWidget(self.label_SYT)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Searching)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(140, 250, 241, 31))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_CHECK = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_CHECK.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_CHECK.setObjectName("gridLayout_CHECK")
        self.pushButton_CHECK = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_CHECK.setObjectName("pushButton_CHECK")
        self.gridLayout_CHECK.addWidget(self.pushButton_CHECK, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Searching)
        self.textBrowser.setGeometry(QtCore.QRect(30, 290, 471, 401))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Searching)
        QtCore.QMetaObject.connectSlotsByName(Searching)

    def retranslateUi(self, Searching):
        _translate = QtCore.QCoreApplication.translate
        Searching.setWindowTitle(_translate("Searching", "Searching"))
        self.label_Search_To.setText(_translate("Searching", "Search To:"))
        self.label_Search_From.setText(_translate("Searching", "Search From:"))
        self.label_Account.setText(_translate("Searching", "Account:"))
        self.label_Currency.setText(_translate("Searching", "Currency:"))
        self.comboBox_Account.setItemText(0, _translate("Searching", "Saving"))
        self.comboBox_Account.setItemText(1, _translate("Searching", "Current"))
        self.comboBox_Currency.setItemText(0, _translate("Searching", "HKD"))
        self.comboBox_Currency.setItemText(1, _translate("Searching", "USD"))
        self.comboBox_Currency.setItemText(2, _translate("Searching", "RMB"))
        self.label_SYT.setText(_translate("Searching", "Searching Your Transacions"))
        self.pushButton_CHECK.setText(_translate("Searching", "Check"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Searching = QtWidgets.QDialog()
    ui = Ui_Searching()
    ui.setupUi(Searching)
    Searching.show()
    sys.exit(app.exec_())
