# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hugo/Desktop/project 3278/show all ac.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Yourac(object):
    def setupUi(self, Yourac):
        Yourac.setObjectName("Yourac")
        Yourac.resize(499, 575)
        self.buttonBox = QtWidgets.QDialogButtonBox(Yourac)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textBrowser = QtWidgets.QTextBrowser(Yourac)
        self.textBrowser.setGeometry(QtCore.QRect(30, 10, 401, 221))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Yourac)
        self.buttonBox.accepted.connect(Yourac.accept)
        self.buttonBox.rejected.connect(Yourac.reject)
        QtCore.QMetaObject.connectSlotsByName(Yourac)

    def retranslateUi(self, Yourac):
        _translate = QtCore.QCoreApplication.translate
        Yourac.setWindowTitle(_translate("Yourac", "All Accounts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Yourac = QtWidgets.QDialog()
    ui = Ui_Yourac()
    ui.setupUi(Yourac)
    Yourac.show()
    sys.exit(app.exec_())
