# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin/ui_files/admin_login_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admin_transation(object):
    def setupUi(self, admin_transation):
        admin_transation.setObjectName("admin_transation")
        admin_transation.resize(518, 712)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(admin_transation)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(130, 150, 311, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.formLayout = QtWidgets.QFormLayout(self.gridLayoutWidget_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_Search_From = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_Search_From.setObjectName("label_Search_From")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Search_From)
        self.dateEdit_Search_From = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        self.dateEdit_Search_From.setObjectName("dateEdit_Search_From")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit_Search_From)
        self.label_Search_To = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_Search_To.setObjectName("label_Search_To")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Search_To)
        self.dateEdit_Search_To = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        self.dateEdit_Search_To.setObjectName("dateEdit_Search_To")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_Search_To)
        self.verticalLayoutWidget = QtWidgets.QWidget(admin_transation)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 20, 171, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_SYT = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_SYT.setObjectName("label_SYT")
        self.verticalLayout.addWidget(self.label_SYT)
        self.user_search = QtWidgets.QPlainTextEdit(admin_transation)
        self.user_search.setGeometry(QtCore.QRect(200, 110, 241, 31))
        self.user_search.setObjectName("user_search")
        self.label_user = QtWidgets.QLabel(admin_transation)
        self.label_user.setGeometry(QtCore.QRect(138, 110, 61, 35))
        self.label_user.setObjectName("label_user")
        self.transaction_table = QtWidgets.QTableView(admin_transation)
        self.transaction_table.setGeometry(QtCore.QRect(20, 270, 481, 421))
        self.transaction_table.setObjectName("transaction_table")
        self.pushButton_CHECK = QtWidgets.QPushButton(admin_transation)
        self.pushButton_CHECK.setGeometry(QtCore.QRect(160, 220, 239, 23))
        self.pushButton_CHECK.setObjectName("pushButton_CHECK")

        self.retranslateUi(admin_transation)
        QtCore.QMetaObject.connectSlotsByName(admin_transation)

    def retranslateUi(self, admin_transation):
        _translate = QtCore.QCoreApplication.translate
        admin_transation.setWindowTitle(_translate("admin_transation", "Searching"))
        self.label_Search_From.setText(_translate("admin_transation", "Search From:"))
        self.label_Search_To.setText(_translate("admin_transation", "Search To:"))
        self.label_SYT.setText(_translate("admin_transation", " Login History Search"))
        self.label_user.setText(_translate("admin_transation", "User:"))
        self.pushButton_CHECK.setText(_translate("admin_transation", "Check"))
