# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin/ui_files/admin_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_account(object):
    def setupUi(self, Admin_account):
        Admin_account.setObjectName("Admin_account")
        Admin_account.resize(500, 423)
        self.profile_table = QtWidgets.QTableWidget(Admin_account)
        self.profile_table.setGeometry(QtCore.QRect(20, 50, 361, 321))
        self.profile_table.setObjectName("profile_table")
        self.profile_table.setColumnCount(0)
        self.profile_table.setRowCount(0)
        self.label = QtWidgets.QLabel(Admin_account)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 31))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Admin_account)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 50, 91, 112))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Search = QtWidgets.QPushButton(self.layoutWidget)
        self.Search.setObjectName("Search")
        self.verticalLayout.addWidget(self.Search)
        self.Insert = QtWidgets.QPushButton(self.layoutWidget)
        self.Insert.setObjectName("Insert")
        self.verticalLayout.addWidget(self.Insert)
        self.Edit = QtWidgets.QPushButton(self.layoutWidget)
        self.Edit.setObjectName("Edit")
        self.verticalLayout.addWidget(self.Edit)
        self.Delete = QtWidgets.QPushButton(self.layoutWidget)
        self.Delete.setObjectName("Delete")
        self.verticalLayout.addWidget(self.Delete)

        self.retranslateUi(Admin_account)
        QtCore.QMetaObject.connectSlotsByName(Admin_account)

    def retranslateUi(self, Admin_account):
        _translate = QtCore.QCoreApplication.translate
        Admin_account.setWindowTitle(_translate("Admin_account", "Profile"))
        self.label.setText(_translate("Admin_account", "Profile"))
        self.Search.setText(_translate("Admin_account", "Search"))
        self.Insert.setText(_translate("Admin_account", "Insert"))
        self.Edit.setText(_translate("Admin_account", "Edit"))
        self.Delete.setText(_translate("Admin_account", "Delete"))
