# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin/ui_files/admin_accounts.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_account(object):
    def setupUi(self, Admin_account):
        Admin_account.setObjectName("Admin_account")
        Admin_account.resize(500, 423)
        self.tableWidget = QtWidgets.QTableWidget(Admin_account)
        self.tableWidget.setGeometry(QtCore.QRect(20, 50, 361, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(Admin_account)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 31))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Admin_account)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 50, 91, 112))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(Admin_account)
        QtCore.QMetaObject.connectSlotsByName(Admin_account)

    def retranslateUi(self, Admin_account):
        _translate = QtCore.QCoreApplication.translate
        Admin_account.setWindowTitle(_translate("Admin_account", "Profile"))
        self.label.setText(_translate("Admin_account", "Accounts"))
        self.pushButton_4.setText(_translate("Admin_account", "Search"))
        self.pushButton.setText(_translate("Admin_account", "Insert"))
        self.pushButton_2.setText(_translate("Admin_account", "Edit"))
        self.pushButton_3.setText(_translate("Admin_account", "Delete"))
