# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from customer.pyfile.Transfer import Ui_Transfer
from customer.pyfile.Show_All_Account import Ui_Yourac
from customer.pyfile.Profile import Ui_Profile
from customer.pyfile.Login_History import Ui_LoginHistory
from customer.pyfile.Search_Transactions import Ui_Searching
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QWidget, QMessageBox)

import mysql.connector

class Customer_Main(object):
    def __init__(self, username):
        super().__init__()
        self.username = username
        self.mycon = mysql.connector.connect(host="localhost",
                                             user="root",
                                             passwd="@Johnny123",
                                             database="sysDB")
        self.cursor = self.mycon.cursor()
        select = "SELECT * " \
                 "FROM CUSTOMER " \
                 "WHERE username=%s"
        self.cursor.execute(select, (self.username,))
        result = self.cursor.fetchall()
        (_, self.last_name, self.first_name, _, self.last_login_time, self.last_login_date) = result[0]
        print(self.last_name, self.first_name, str(self.last_login_time), str(self.last_login_date))

    def transfer(self):
        self.window = QtWidgets.QDialog()
        # TODO: transfer sql
        self.ui = Ui_Transfer()
        self.ui.setupUi(self.window)
        self.window.show()

    def showAccount(self):
        self.window = QtWidgets.QDialog()
        # TODO: get all accounts
        accounts = ""
        self.ui = Ui_Yourac(accounts)
        self.ui.setupUi(self.window)
        self.window.show()

    def profile(self):
        self.window = QtWidgets.QDialog()
        # TODO: show profile
        self.ui = Ui_Profile()
        self.ui.setupUi(self.window)
        self.window.show()

    def loginhistory(self):
        self.window = QtWidgets.QDialog()
        # TODO: login history
        login_history = ""
        self.ui = Ui_LoginHistory(login_history)
        self.ui.setupUi(self.window)
        self.window.show()

    def searching(self):
        self.window = QtWidgets.QDialog()
        # TODO
        self.ui = Ui_Searching()
        self.ui.setupUi(self.window)
        self.window.show()

    def addAccount(self):

        pass

    def pop_ask_window(self, text, question):
        message = QMessageBox()
        message.setText(question)
        message.setStyleSheet("QMessageBox{"
                              "background-color: rgba(41,49,55,0.85);"
                              "}"
                              "QLabel{"
                              "color: #FFFFFF;"
                              "}")
        message.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        message.setDefaultButton(QMessageBox.No)
        return message.exec()

    def close(self):
        if (self.pop_ask_window("Window Close",
                           "Are you sure you want to close the window?") == QMessageBox.Yes):
            self.window.close()
            pass
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 450)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: #293137")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(5000, 5000))
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Logout.setGeometry(QtCore.QRect(470, 350, 101, 32))
        self.pushButton_Logout.setMaximumSize(QtCore.QSize(171, 16777215))
        self.pushButton_Logout.setStyleSheet("color:white;\n"
                                             "border:1px solid rgb(168, 168, 170);\n"
                                             "border-radius: 15px;")
        self.pushButton_Logout.setObjectName("pushButton_Logout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 40, 471, 29))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.pushButton_AddAccount = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AddAccount.setGeometry(QtCore.QRect(230, 170, 141, 32))
        self.pushButton_AddAccount.setStyleSheet("color:white;\n"
                                                 "border:1px solid rgb(168, 168, 170);\n"
                                                 "border-radius: 15px;")
        self.pushButton_AddAccount.setObjectName("pushButton_AddAccount")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
                                   "border-bottom: 1.5px  solid white")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 111, 101))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setIndent(-1)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 130, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
                                   "border-bottom: 1.5px  solid white")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 130, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;\n"
                                   "border-bottom: 1.5px  solid white")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_Check_Transactions = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Check_Transactions.setGeometry(QtCore.QRect(50, 210, 141, 32))
        self.pushButton_Check_Transactions.setMaximumSize(QtCore.QSize(481, 16777215))
        self.pushButton_Check_Transactions.setStyleSheet("color:white;\n"
                                              "border:1px solid rgb(168, 168, 170);\n"
                                              "border-radius: 15px;")
        self.pushButton_Check_Transactions.setObjectName("pushButton_Balance")
        self.pushButton_CheckAllAccount = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CheckAllAccount.setGeometry(QtCore.QRect(50, 170, 141, 32))
        self.pushButton_CheckAllAccount.setMaximumSize(QtCore.QSize(481, 16777215))
        self.pushButton_CheckAllAccount.setStyleSheet("color:white;\n"
                                                      "border:1px solid rgb(168, 168, 170);\n"
                                                      "border-radius: 15px;")
        self.pushButton_CheckAllAccount.setObjectName("pushButton_CheckAllAccount")
        self.pushButton_Profile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Profile.setGeometry(QtCore.QRect(410, 170, 141, 32))
        self.pushButton_Profile.setMaximumSize(QtCore.QSize(481, 16777215))
        self.pushButton_Profile.setStyleSheet("color:white;\n"
                                              "border:1px solid rgb(168, 168, 170);\n"
                                              "border-radius: 15px;")
        self.pushButton_Profile.setObjectName("pushButton_Profile")
        self.pushButton_Transfer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Transfer.setGeometry(QtCore.QRect(50, 250, 141, 32))
        self.pushButton_Transfer.setMaximumSize(QtCore.QSize(481, 16777215))
        self.pushButton_Transfer.setStyleSheet("color:white;\n"
                                               "border:1px solid rgb(168, 168, 170);\n"
                                               "border-radius: 15px;")
        self.pushButton_Transfer.setObjectName("pushButton_Transfer")
        self.pushButton_LoginHistory = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LoginHistory.setGeometry(QtCore.QRect(410, 210, 141, 32))
        self.pushButton_LoginHistory.setMaximumSize(QtCore.QSize(481, 16777215))
        self.pushButton_LoginHistory.setStyleSheet("color:white;\n"
                                                   "border:1px solid rgb(168, 168, 170);\n"
                                                   "border-radius: 15px;")
        self.pushButton_LoginHistory.setObjectName("pushButton_LoginHistory")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 360, 300, 16))
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCheck_All_account = QtWidgets.QAction(MainWindow)
        self.actionCheck_All_account.setObjectName("actionCheck_All_account")
        self.actionProfile = QtWidgets.QAction(MainWindow)
        self.actionProfile.setObjectName("actionProfile")
        self.actionLogin_History = QtWidgets.QAction(MainWindow)
        self.actionLogin_History.setObjectName("actionLogin_History")
        self.actionAdd_Account = QtWidgets.QAction(MainWindow)
        self.actionAdd_Account.setObjectName("actionAdd_Account")
        self.actionBalence = QtWidgets.QAction(MainWindow)
        self.actionBalence.setObjectName("actionBalence")
        self.actionTransfer = QtWidgets.QAction(MainWindow)
        self.actionTransfer.setObjectName("actionTransfer")

        self.pushButton_CheckAllAccount.clicked.connect(self.showAccount)
        self.pushButton_Check_Transactions.clicked.connect(self.searching)
        self.pushButton_Transfer.clicked.connect(self.transfer)
        self.pushButton_Profile.clicked.connect(self.profile)
        self.pushButton_LoginHistory.clicked.connect(self.loginhistory)
        self.pushButton_Logout.clicked.connect(self.close)
        self.pushButton_AddAccount.clicked.connect(self.addAccount)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Logout.setText(_translate("MainWindow", "Logout"))
        self.label.setText(_translate("MainWindow", f"Welcome back,  {self.first_name} {self.last_name}"))
        self.pushButton_AddAccount.setText(_translate("MainWindow", "Add Account"))
        self.label_2.setText(_translate("MainWindow", "Banking"))
        self.label_4.setText(_translate("MainWindow", "Assistant"))
        self.label_5.setText(_translate("MainWindow", "Setting"))
        self.pushButton_Check_Transactions.setText(_translate("MainWindow", "Transaction History"))
        self.pushButton_CheckAllAccount.setText(_translate("MainWindow", "Check All Account"))
        self.pushButton_Profile.setText(_translate("MainWindow", "Profile"))
        self.pushButton_Transfer.setText(_translate("MainWindow", "Transfer"))
        self.pushButton_LoginHistory.setText(_translate("MainWindow", "Login History"))
        self.label_6.setText(_translate("MainWindow", f"Last Login: {self.last_login_time} {self.last_login_date}"))
        self.actionCheck_All_account.setText(_translate("MainWindow", "Check All account"))
        self.actionProfile.setText(_translate("MainWindow", "Profile"))
        self.actionLogin_History.setText(_translate("MainWindow", "Login History"))
        self.actionAdd_Account.setText(_translate("MainWindow", "Add Account"))
        self.actionBalence.setText(_translate("MainWindow", "Balance"))
        self.actionTransfer.setText(_translate("MainWindow", "Transfer"))