# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer/ui_file_copy/Login_History.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginHistory(object):
    def __init__(self, login_history):
        self.login_history = login_history

    def setupUi(self, LoginHistory):
        LoginHistory.setObjectName("LoginHistory")
        LoginHistory.resize(381, 252)
        LoginHistory.setStyleSheet("background-color: #293137")
        self.textBrowser_loginhistory = QtWidgets.QTextBrowser(LoginHistory)
        self.textBrowser_loginhistory.setGeometry(QtCore.QRect(20, 20, 341, 211))
        self.textBrowser_loginhistory.setStyleSheet("border:1px solid grey")
        self.textBrowser_loginhistory.setObjectName("textBrowser_loginhistory")

        self.retranslateUi(LoginHistory)
        QtCore.QMetaObject.connectSlotsByName(LoginHistory)

    def retranslateUi(self, LoginHistory):
        _translate = QtCore.QCoreApplication.translate
        LoginHistory.setWindowTitle(_translate("LoginHistory", "Login History"))
