# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer/ui_file_copy/Profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Profile(object):
    def setupUi(self, Profile):
        Profile.setObjectName("Profile")
        Profile.resize(402, 382)
        Profile.setStyleSheet("background-color: #293137")
        self.textBrowser = QtWidgets.QTextBrowser(Profile)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 361, 341))
        self.textBrowser.setStyleSheet("color:white;border:1px solid grey;")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Profile)
        QtCore.QMetaObject.connectSlotsByName(Profile)

    def retranslateUi(self, Profile):
        _translate = QtCore.QCoreApplication.translate
        Profile.setWindowTitle(_translate("Profile", "Profile"))
