# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer/ui_file_copy/Show_All_Account.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Yourac(object):
    def __init__(self, accounts):
        self.accounts = accounts
    def setupUi(self, Yourac):
        Yourac.setObjectName("Yourac")
        Yourac.resize(444, 262)
        Yourac.setStyleSheet("background-color: #293137")
        self.textBrowser = QtWidgets.QTextBrowser(Yourac)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 401, 221))
        self.textBrowser.setStyleSheet("color:white;border:1px solid grey;")
        self.textBrowser.setOverwriteMode(True)
        self.textBrowser.setObjectName("textBrowser")

        self.textBrowser.setText(self.accounts)

        self.retranslateUi(Yourac)
        QtCore.QMetaObject.connectSlotsByName(Yourac)

    def retranslateUi(self, Yourac):
        _translate = QtCore.QCoreApplication.translate
        Yourac.setWindowTitle(_translate("Yourac", "All Accounts"))
        self.textBrowser.setHtml(_translate("Yourac", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser.setPlaceholderText(_translate("Yourac", "You have not added any account yet."))
