# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer/ui_file_copy/Transfer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Transfer(object):
    def setupUi(self, Transfer):
        Transfer.setObjectName("Transfer")
        Transfer.resize(642, 454)
        Transfer.setMouseTracking(True)
        Transfer.setStyleSheet("background-color: #293137")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Transfer)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(40, 80, 551, 161))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(15)
        self.formLayout_2.setVerticalSpacing(22)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_amount_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_amount_2.setStyleSheet("color:white")
        self.lineEdit_amount_2.setObjectName("lineEdit_amount_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_amount_2)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_amount = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_amount.setStyleSheet("color:white")
        self.lineEdit_amount.setObjectName("lineEdit_amount")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_amount)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setStyleSheet("color:white")
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_currency_2 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_currency_2.setStyleSheet("color:white;width:30px;")
        self.comboBox_currency_2.setObjectName("comboBox_currency_2")
        self.comboBox_currency_2.addItem("")
        self.comboBox_currency_2.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_currency_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setStyleSheet("color:white")
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_currency = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_currency.setStyleSheet("color:white;width:30px")
        self.comboBox_currency.setObjectName("comboBox_currency")
        self.comboBox_currency.addItem("")
        self.comboBox_currency.addItem("")
        self.comboBox_currency.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_currency)
        self.pushButton_TRANSFER = QtWidgets.QPushButton(Transfer)
        self.pushButton_TRANSFER.setGeometry(QtCore.QRect(480, 250, 101, 24))
        self.pushButton_TRANSFER.setStyleSheet("color:white; border:1px solid white;border-radius:10px")
        self.pushButton_TRANSFER.setObjectName("pushButton_TRANSFER")
        self.pushButton_CANCEL = QtWidgets.QPushButton(Transfer)
        self.pushButton_CANCEL.setGeometry(QtCore.QRect(370, 250, 101, 24))
        self.pushButton_CANCEL.setStyleSheet("color:white; border:1px solid white;border-radius:10px")
        self.pushButton_CANCEL.setObjectName("pushButton_CANCEL")

        self.pushButton_CANCEL.clicked.connect(Transfer.reject)

        self.retranslateUi(Transfer)
        QtCore.QMetaObject.connectSlotsByName(Transfer)

    def retranslateUi(self, Transfer):
        _translate = QtCore.QCoreApplication.translate
        Transfer.setWindowTitle(_translate("Transfer", "Transfer"))
        self.label_2.setText(_translate("Transfer", "ACCOUNT NAME"))
        self.lineEdit_amount_2.setPlaceholderText(_translate("Transfer", "his/her username"))
        self.label.setText(_translate("Transfer", "ENTER AMOUNT TO DESPOSIT"))
        self.lineEdit_amount.setPlaceholderText(_translate("Transfer", "amount"))
        self.label_5.setText(_translate("Transfer", "CHOOSE ACCOUNT"))
        self.comboBox_currency_2.setItemText(0, _translate("Transfer", "Saving"))
        self.comboBox_currency_2.setItemText(1, _translate("Transfer", "Current"))
        self.label_4.setText(_translate("Transfer", "CHOOSE CURRENCY"))
        self.comboBox_currency.setItemText(0, _translate("Transfer", "HKD"))
        self.comboBox_currency.setItemText(1, _translate("Transfer", "USD"))
        self.comboBox_currency.setItemText(2, _translate("Transfer", "CNY"))
        self.pushButton_TRANSFER.setText(_translate("Transfer", "TRANSFER"))
        self.pushButton_CANCEL.setText(_translate("Transfer", "CANCEL"))
